### ISSUE TITLE
last_wal_received info get failed

### ISSUE THREAD

**Issue by qguan-aa** [hamann/check-barman#8]
Hi, 
First, very good plugin for us, awesome job! We meet some problems recently
barman --version
1.4.0

ssh works fine
pg works fine
backups_available works fine
last_wal_received fail with error
failed_backups works fine

./check-barman.rb -a last_wal_received -s u-master -w 300 -c 600
/var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:125:in `wal_files': undefined method `downcase' for :gzip:Symbol (NoMethodError)
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:121:in `each'
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:121:in `wal_files'
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:71:in `backups'
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:68:in `each'
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:68:in `backups'
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/cli_command.rb:54:in `backup'
	from /var/lib/gems/1.8/gems/rbarman-0.0.14/lib/rbarman/backup.rb:298:in `by_id'
	from ./check-barman.rb:82:in `check_last_wal_received'
	from ./check-barman.rb:235

latest backup info
barman show-backup u-master latest
Backup 20150825T153001:
  Server Name            : u-master
  Status                 : DONE
  PostgreSQL Version     : 90404
  PGDATA directory       : /var/lib/postgresql/9.4/main

  Base backup information:
    Disk usage           : 22.5 GiB (22.5 GiB with WALs)
    Incremental size     : 22.5 GiB (-0.00%)
    Timeline             : 1
    Begin WAL            : 000000010000002B0000006F
    End WAL              : 000000010000002B00000079
    WAL number           : 11
    WAL compression ratio: 68.10%
    Begin time           : 2015-08-25 15:30:01.470980-07:00
    End time             : 2015-08-25 16:02:05.825740-07:00
    Begin Offset         : 5025552
    End Offset           : 0
    Begin XLOG           : 2B/6F4CAF10
    End XLOG             : 2B/7A000000

  WAL information:
    No of files          : 199
    Disk usage           : 1.1 GiB
    WAL rate             : 0.35/hour
    Compression ratio    : 63.54%
    Last available       : 000000010000002C00000040

  Catalog information:
    Retention Policy     : VALID
    Previous Backup      : 20150821T153001
    Next Backup          : - (this is the latest base backup)

barman status u-master
Server u-master:
	Description: U master PostgreSQL Database
	PostgreSQL version: 9.4.4
	pgespresso extension: Available
	PostgreSQL Data directory: /var/lib/postgresql/9.4/main
	PostgreSQL 'archive_command' setting: if [ ! -f /var/lib/postgresql/stop_archive ];  then rsync -a -e "ssh -p 20002" %p barman@prod-pgbackup-1:/var/lib/barman/u-master/incoming/%f; else cd .; fi
	Last archived WAL: 000000010000002C00000040
	Failures of WAL archiver: 0
	Retention policies: enforced (mode: auto, retention: RECOVERY WINDOW OF 1 WEEKS, WAL retention: MAIN)
	No. of available backups: 3
	First available backup: 20150818T153001
	Last available backup: 20150825T153001
	Minimum redundancy requirements: satisfied (3/0)

Is it because new barman version output changed?

**Comment by hamann** [comment]
Thanks for reporting!
I released a new rbarman version which should fix that issue.
In case you installed rbarman with gem, please do a
```sh
$ gem install rbarman
```
otherwise pull and ran bundle.

Does this work for you?
